POST http://localhost:3001/recipes/create
Content-Type: application/json

{
    "name": "Steak",
    "ingredients": ["beef", "salt", "pepper"],
    "description": "Cook in the bbq at high heat.",
    "image": "https://www.seriouseats.com/thmb/WzQz05gt5witRGeOYKTcTqfe1gs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/butter-basted-pan-seared-steaks-recipe-hero-06-03b1131c58524be2bd6c9851a2fbdbc3.jpg",
    "cookingTime": 30,
    "creator": "64df8a2aa48f293a10c51788"
}

###
GET http://localhost:3001/recipes/

###

POST http://localhost:3001/recipes/save
Content-Type: application/json

{
    "recipeID": "64df51185edc48ef35bd783a",
    "userID": "64df8a2aa48f293a10c51788"
}